version: '3'

services:
  web:
    image: akoval88/piesecrets_web:latest
    command: python manage.py runserver 0.0.0.0:8000
    # command: gunicorn piesecrets.wsgi:application --bind 0.0.0.0:8000
    ports:
        - 8000:8000
    env_file:
        - ./.env.prod
    depends_on:
        - db

  db:
    image: postgres:12-alpine
    environment:
        - POSTGRES_DB=piesecrets
        - POSTGRES_USER=piesecrets
        - POSTGRES_PASSWORD=6UavraTts7nB
    ports:
        - "5432:5432"