version: '3'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.build
        # command: wagtail start piesecrets
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
            - "3000:3000"
        depends_on:
            - db

    db:
        image: postgres:12
        environment: 
            - POSTGRES_DB=piesecrets
            - POSTGRES_USER=piesecrets
            - POSTGRES_PASSWORD=6UavraTts7nB
        ports:
            - "5432:5432"