# Generated by Django 2.2.13 on 2020-06-14 15:56

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('piesecrets', '0005_auto_20200614_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='ingredients',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, verbose_name='ingredients'),
        ),
        migrations.AlterField(
            model_name='postpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('embedded_video', wagtail.embeds.blocks.EmbedBlock(icon='media'))], blank=True, null=True),
        ),
    ]
